#include "../../common/linux/hc/hc.h"
#include "../../common/linux/hc/libc.h"
#include "../../common/linux/hc/libc.c"
#include "../../common/linux/hc/wrappers.h"
#include "../../common/linux/allocator.h"
#include "../../common/linux/debug.h"

#include "client/generatedHtml.h"
#include "../common/include/protocol.h"
#include "../common/include/timespec.h"
#include "../../common/server/include/base64.h"
#include "../../common/server/include/fileResponse.h"
#include "../../common/server/include/serverCallbacks.h"
#include "../../common/server/include/serverClient.h"
#include "../../common/server/include/server.h"
#include "include/chessClient.h"
#include "include/chessRoom.h"
#include "include/chess.h"

#include "src/main.c"
#include "src/chess.c"
#include "src/chessRoom.c"
#include "src/chessClient.c"
#include "../../common/server/src/server.c"
#include "../../common/server/src/serverCallbacks.c"
#include "../../common/server/src/serverClient.c"
#include "../../common/server/src/fileResponse.c"
#include "../../common/server/src/base64.c"
